version = 0.1

[default.deploy.parameters]
stack_name = "ticf-integration"
region = "eu-west-2"
tags = "project=\"di-txma-ticf-integration\" stage=\"build\""
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides=[
    "Environment=build",
    "CodeSigningConfigArn=none",
    "PermissionsBoundary=none"
]

[build.deploy.parameters]
stack_name = "ticf-integration"
region = "eu-west-2"
tags = "project=\"di-txma-ticf-integration\" stage=\"build\""
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides=[
    "Environment=build",
    "CodeSigningConfigArn=none",
    "PermissionsBoundary=none"
]

[dev.deploy.parameters]
stack_name = "ticf-integration"
egion = "eu-west-2"
tags = "project=\"di-txma-ticf-integration\" stage=\"dev\""
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides=[
    "Environment=dev",
    "CodeSigningConfigArn=none",
    "PermissionsBoundary=none"
]
