Parameters:
  AnalysisBucketName:
    Description: The name of the Analysis Bucket
    Type: String
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
  StackName:
    Description: The name of the parent stack
    Type: String

Resources:
  AuditAnalysisTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: '{{resolve:ssm:AuditAnalysisDatabaseName}}'
      TableInput:
        Description: Table contains event message data to be analysed
        Name:
          !Join [
            '',
            [
              !Join ['', !Split ['-', !Ref StackName]],
              !Sub '_${Environment}_analysis_table'
            ]
          ]
        Parameters:
          has_encrypted_data: false
          projection.enabled: true
          projection.datetime.type: date
          projection.datetime.range: '2022/01/01/00,NOW'
          projection.datetime.format: 'yyyy/MM/dd/HH'
          projection.datetime.interval: 1
          projection.datetime.interval.unit: HOURS
          storage.location.template:
            !Join [
              '',
              ['s3://', !Ref AnalysisBucketName, '/firehose/${datetime}/']
            ]
        PartitionKeys:
          - { Name: 'datetime', Type: string }
        StorageDescriptor:
          Columns:
            - { Name: 'event_id', Type: string }
            - { Name: 'govuk_signin_journey_id', Type: string }
            - { Name: 'session_id', Type: string }
            - { Name: 'user_id', Type: string }
            - { Name: 'client_id', Type: string }
            - { Name: 'timestamp', Type: bigint }
            - { Name: 'timestamp_formatted', Type: string }
            - { Name: 'event_name', Type: string }
            - { Name: 'component_id', Type: string }
            - { Name: 'user', Type: string }
            - { Name: 'platform', Type: string }
            - { Name: 'restricted', Type: string }
            - { Name: 'extensions', Type: string }
          Compressed: true
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${AnalysisBucketName}/firehose/
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
              {
                'ignore.malformed.json': true,
                'serialiazation.format': 1,
                'field.delim': ''
              }
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
          StoredAsSubDirectories: false
        TableType: EXTERNAL_TABLE

Outputs:
  AuditAnalysisTableArn:
    Value: !Sub arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:table/{{resolve:ssm:AuditAnalysisDatabaseName}}/${AuditAnalysisTable}
  AuditAnalysisTableName:
    Value: !Ref AuditAnalysisTable
