Parameters:
  AnalysisBucketName:
    Description: The name of the Analysis Bucket
    Type: String
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
  StackName:
    Description: The name of the parent stack
    Type: String

Resources:

Outputs:
  AuditAnalysisTableArn:
    Value: !Sub arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:table/{{resolve:ssm:AuditAnalysisDatabaseName}}/${AuditAnalysisTable}
  AuditAnalysisTableName:
    Value: !Ref AuditAnalysisTable
