Parameters:
  AuditBucketArn:
    Description: ARN of the Audit bucket
    Type: String
  DeployDevResources:
    Description: Flag to deploy dev infrastructure
    Type: String
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
  PermissionsBoundary:
    Description: The ARN of the permissions boundary to apply to any role created by the template
    Type: String
  StackName:
    Description: The name of the parent stack
    Type: String

Conditions:
  DeployDevResources: !Equals [true, !Ref DeployDevResources]
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, none]]

Resources:

Outputs:
  AnalysisBucketArn:
    Value: !GetAtt AnalysisBucket.Arn
  AnalysisBucketName:
    Value: !Ref AnalysisBucket
  BatchJobsRoleArn:
    Value: !GetAtt BatchJobsRole.Arn
