Parameters:
  AuditBucketArn:
    Description: ARN of the Audit bucket
    Type: String
  DeployDevResources:
    Description: Flag to deploy dev infrastructure
    Type: String
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
  PermissionsBoundary:
    Description: The ARN of the permissions boundary to apply to any role created by the template
    Type: String
  StackName:
    Description: The name of the parent stack
    Type: String

Conditions:
  DeployDevResources: !Equals [true, !Ref DeployDevResources]
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, none]]

Resources:
  AnalysisBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${StackName}-${Environment}-analysis-bucket
      LifecycleConfiguration:
        Rules:
          - Id: AnalysisCleanupRule
            Status: Enabled
            ExpirationInDays: 30
      LoggingConfiguration:
        DestinationBucketName: !Ref AnalysisLogsBucket
        LogFilePrefix: String
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  AnalysisLogsBucket:
    #checkov:skip=CKV_AWS_18:This is the logs bucket
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${StackName}-${Environment}-analysis-logs
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  BatchJobsRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary:
        !If [
          UsePermissionsBoundary,
          !Ref PermissionsBoundary,
          !Ref AWS::NoValue
        ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - batchoperations.s3.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowS3GlacierRestore
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowAuditBucketRestore
                Effect: Allow
                Action:
                  - s3:RestoreObject
                Resource:
                  - !Sub ${AuditBucketArn}/*
              - Sid: AllowManifestBucketRead
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - !Join [
                      '/',
                      ['{{resolve:ssm:BatchJobManifestBucketArn}}', '*']
                    ]
        - PolicyName: AllowS3Copy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowAnalysisBucketWrite
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:PutObjectTagging
                Resource:
                  - !Join ['/', [!GetAtt AnalysisBucket.Arn, '*']]
              - Sid: AllowAuditBucketRead
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectAcl
                  - s3:GetObjectTagging
                  - s3:ListBucket
                Resource:
                  - !Sub ${AuditBucketArn}/*

  EmptyS3Buckets:
    Condition: DeployDevResources
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: '{{resolve:ssm:EmptyS3BucketsFunctionArn}}'

Outputs:
  AnalysisBucketArn:
    Value: !GetAtt AnalysisBucket.Arn
  AnalysisBucketName:
    Value: !Ref AnalysisBucket
  BatchJobsRoleArn:
    Value: !GetAtt BatchJobsRole.Arn
