name: Pre-merge Build and Test

on:
  [push]
  # pull_request:
  #   branches: [ main ]

jobs:
  run_tests_and_validation:
    name: Run tests and validation
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_VALIDATE_ROLE_ARN }}
          aws-region: eu-west-2
      - name: Install Yarn v3
        run: corepack enable
      - name: Check Yarn cache
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Run linting
        if: always()
        run: yarn lint
      - name: Run tests
        if: always()
        run: yarn test
      - name: Build Lambda functions
        if: always()
        run: yarn build
      - name: Validate SAM template
        if: always()
        run: sam validate --config-env build
