name: Pre-merge Build and Test
on: [push]
jobs:
  run_linting:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Yarn v3
        run: corepack enable
      - name: Check Yarn cache
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Run linting
        run: yarn lint
